export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const ORDER_BURGER = 'ORDER_BURGER';
export const ORDER_BURGER_FAILED = 'ORDER_BURGER_FAILED';
export const ORDER_POSTED = 'ORDER_POSTED';
export const ORDER_INIT = 'ORDER_INIT';