export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';

export const ORDER_BURGER = 'ORDER_BURGER';
export const ORDER_INIT = 'ORDER_INIT';
export const ORDER_BURGER_FAILED = 'ORDER_BURGER_FAILED';
export const ORDER_POSTED = 'ORDER_POSTED';

export const PLACE_ORDER = 'PLACE_ORDER';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_DONE = "FETCH_ORDERS_DONE";
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INIT_LOGOUT = 'AUTH_INIT_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INIT = 'AUTH_INIT';
export const SET_AUTH_REDIRECT = "SET_AUTH_REDIRECT";
export const CHECK_LOGIN_TIMEOUT = 'CHECK_LOGIN_TIMEOUT';
export const CHECK_AUTH_EXPIRE = 'CHECK_AUTH_EXPIRE';